"""Shared test fixtures. FROZEN in Phase 0 — add your own ``tests/test_<area>.py``,
do not edit this file on a Phase 1 branch.
"""
from __future__ import annotations

from datetime import datetime, timezone

import pytest

from security_preview.models import (
    Confidence,
    DependencyFinding,
    Finding,
    RiskLevel,
    ScanResult,
)


@pytest.fixture
def make_finding():
    def _make(**over) -> Finding:
        base = {
            "rule_id": "py.sqli",
            "name": "SQL Injection",
            "severity": RiskLevel.CRITICAL,
            "confidence": Confidence.HIGH,
            "category": "Injection",
            "cwe_id": "CWE-89",
            "file_path": "api/reports.py",
            "line": 142,
            "code_snippet": 'cur.execute(f"... {owner}")',
            "description": "User input flows into a SQL string.",
            "remediation_vulnerable": 'cur.execute(f"... {owner}")',
            "remediation_secure": 'cur.execute("... %s", (owner,))',
            "cve_ids": [],
        }
        base.update(over)
        return Finding(**base)

    return _make


@pytest.fixture
def make_dependency_finding():
    def _make(**over) -> DependencyFinding:
        base = {
            "ecosystem": "PyPI",
            "package": "pyyaml",
            "version": "5.1",
            "advisory_ids": ["CVE-2020-1747"],
            "severity": RiskLevel.CRITICAL,
            "fixed_version": "5.3.1",
            "source_manifest": "requirements.txt",
            "summary": "Arbitrary code execution via full_load.",
        }
        base.update(over)
        return DependencyFinding(**base)

    return _make


@pytest.fixture
def make_scan_result(make_finding, make_dependency_finding):
    def _make(**over) -> ScanResult:
        base = {
            "target": "/tmp/proj",
            "started_at": datetime(2026, 9, 1, 14, 22, tzinfo=timezone.utc),
            "finished_at": datetime(2026, 9, 1, 14, 22, 3, tzinfo=timezone.utc),
            "findings": [make_finding()],
            "dependency_findings": [make_dependency_finding()],
            "files_scanned": 342,
            "dependencies_scanned": 47,
            "errors": [],
            "partial": False,
        }
        base.update(over)
        return ScanResult(**base)

    return _make


@pytest.fixture
def write_project(tmp_path):
    def _write(files: dict[str, str]) -> str:
        for rel, content in files.items():
            p = tmp_path / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
        return str(tmp_path)

    return _write
