"""Plain-text terminal report."""
from __future__ import annotations

from ..models import ScanResult
from ._shared import (
    SEVERITY_ORDER,
    advisory_url,
    cwe_url,
    rerun_command,
    scanned_line,
    severity_counts,
    snippet_lines,
    sorted_dependency_findings,
    sorted_findings,
)

_RULE = "-" * 60


def render_text(result: ScanResult) -> str:
    findings = sorted_findings(result.findings)
    deps = sorted_dependency_findings(result.dependency_findings)
    lines: list[str] = []

    lines.append(f"security-preview report v{result.tool_version}")
    lines.append(f"target:  {result.target}")
    lines.append(f"scanned: {scanned_line(result)}")
    lines.append("")

    lines.append("SUMMARY")
    for level, count in severity_counts(result):
        lines.append(f"  {level:<9} {count}")
    lines.append(f"  {'DEPS':<9} {len(deps)}  (vulnerable dependencies)")
    lines.append(
        f"  files scanned: {result.files_scanned} | "
        f"dependencies checked: {result.dependencies_scanned}"
    )
    lines.append("")

    if result.partial:
        lines.append(
            f"! PARTIAL - {len(result.errors)} issue(s) recorded during the scan; "
            "code findings are complete. See SKIPPED / ERRORS."
        )
        lines.append("")

    lines.append(f"CODE FINDINGS ({len(findings)})")
    if not findings:
        lines.append("  none")
    lines.append("")
    for level in SEVERITY_ORDER:
        group = [f for f in findings if f.severity is level]
        if not group:
            continue
        lines.append(level.value)
        for f in group:
            lines.append(f"  [{f.rule_id}] {f.name}")
            lines.append(f"    location:   {f.file_path}:{f.line}")
            if f.cwe_id:
                url = cwe_url(f.cwe_id)
                lines.append(f"    cwe:        {f.cwe_id}" + (f" ({url})" if url else ""))
            lines.append(f"    category:   {f.category}")
            lines.append(f"    confidence: {f.confidence.value}")
            lines.append("    snippet:")
            for num, text, hit in snippet_lines(f):
                gutter = f"{num:>4}" if num is not None else "    "
                mark = ">" if hit else " "
                lines.append(f"      {mark}{gutter}| {text}")
            lines.append(f"    what's wrong: {f.description}")
            lines.append(f"    vulnerable:   {f.remediation_vulnerable}")
            lines.append(f"    secure:       {f.remediation_secure}")
            if f.cve_ids:
                lines.append(f"    cves:         {', '.join(f.cve_ids)}")
            lines.append("")

    lines.append(f"VULNERABLE DEPENDENCIES ({len(deps)})")
    if not deps:
        lines.append("  none")
    lines.append("")
    for d in deps:
        lines.append(f"  {d.severity.value:<9} {d.package} {d.version} ({d.ecosystem})")
        if d.advisory_ids:
            joined = ", ".join(f"{a} ({advisory_url(a)})" for a in d.advisory_ids)
            lines.append(f"    advisories: {joined}")
        lines.append(f"    fixed in:   {d.fixed_version or 'no fix available'}")
        lines.append(f"    source:     {d.source_manifest}")
        lines.append(f"    summary:    {d.summary}")
        lines.append("")

    lines.append(f"SKIPPED / ERRORS ({len(result.errors)})")
    if not result.errors:
        lines.append("  none")
    else:
        for e in result.errors:
            lines.append(f"  [{e.stage}] {e.target} - {e.message}")
    lines.append("")

    lines.append(_RULE)
    lines.append(
        f"Generated by security-preview v{result.tool_version} - "
        "deterministic, non-LLM static scan."
    )
    lines.append("Findings are pattern- and dependency-based; treat them as leads, not proof.")
    lines.append(f"Re-run: {rerun_command(result, 'text')}")

    return "\n".join(lines) + "\n"
