"""Shared data model. FROZEN in Phase 0. Every module imports from here.

Do not edit this file on any Phase 1 branch. If a field is missing, note it in
`progress/<area>.md` and the merger will add it.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum

TOOL_VERSION = "0.1.0"


class RiskLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

    @property
    def rank(self) -> int:
        return {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}[self.value]


class Confidence(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

    @property
    def rank(self) -> int:
        return {"HIGH": 0, "MEDIUM": 1, "LOW": 2}[self.value]

    def meets(self, minimum: Confidence) -> bool:
        """True when this confidence is at least as strong as ``minimum``."""
        return self.rank <= minimum.rank


@dataclass(frozen=True)
class Component:
    ecosystem: str          # "PyPI" | "npm" | "Go" | "Maven" | "RubyGems"
    name: str
    version: str
    source_manifest: str    # path relative to scan root, posix separators


@dataclass
class Finding:
    rule_id: str
    name: str
    severity: RiskLevel
    confidence: Confidence
    category: str            # "Injection" | "Crypto" | "Secrets" | "Config" | ...
    cwe_id: str | None
    file_path: str           # relative to scan root, posix separators
    line: int
    code_snippet: str        # secrets already masked by the producer
    description: str
    remediation_vulnerable: str
    remediation_secure: str
    cve_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["severity"] = self.severity.value
        d["confidence"] = self.confidence.value
        return d

    @classmethod
    def from_dict(cls, d: dict) -> Finding:
        d = dict(d)
        d["severity"] = RiskLevel(d["severity"])
        d["confidence"] = Confidence(d["confidence"])
        return cls(**d)


@dataclass
class DependencyFinding:
    ecosystem: str
    package: str
    version: str
    advisory_ids: list[str]      # OSV / GHSA / CVE ids
    severity: RiskLevel
    fixed_version: str | None
    source_manifest: str
    summary: str

    def to_dict(self) -> dict:
        d = asdict(self)
        d["severity"] = self.severity.value
        return d

    @classmethod
    def from_dict(cls, d: dict) -> DependencyFinding:
        d = dict(d)
        d["severity"] = RiskLevel(d["severity"])
        return cls(**d)


@dataclass
class ScanError:
    stage: str              # "walk" | "sast" | "sca" | "enrich"
    target: str
    message: str


class ErrorCollector:
    """Mutable; passed into every stage. Replaces bare ``except: pass``."""

    def __init__(self) -> None:
        self._errors: list[ScanError] = []

    def add(self, stage: str, target: str, message: str) -> None:
        self._errors.append(ScanError(stage=stage, target=target, message=str(message)))

    def to_list(self) -> list[ScanError]:
        return list(self._errors)

    @property
    def partial(self) -> bool:
        return bool(self._errors)


@dataclass
class ScanResult:
    target: str
    started_at: datetime
    finished_at: datetime | None
    findings: list[Finding]
    dependency_findings: list[DependencyFinding]
    files_scanned: int
    dependencies_scanned: int
    errors: list[ScanError]
    partial: bool
    tool_version: str = TOOL_VERSION

    def summary(self) -> dict:
        by_sev = {lvl.value: 0 for lvl in RiskLevel}
        for f in self.findings:
            by_sev[f.severity.value] += 1
        dur = None
        if self.finished_at:
            dur = (self.finished_at - self.started_at).total_seconds()
        return {
            "target": self.target,
            "by_severity": by_sev,
            "total_findings": len(self.findings),
            "vulnerable_dependencies": len(self.dependency_findings),
            "files_scanned": self.files_scanned,
            "dependencies_scanned": self.dependencies_scanned,
            "duration_seconds": dur,
            "partial": self.partial,
            "errors": len(self.errors),
        }

    def to_dict(self) -> dict:
        return {
            "tool_version": self.tool_version,
            "target": self.target,
            "started_at": self.started_at.astimezone(timezone.utc).isoformat(),
            "finished_at": self.finished_at.astimezone(timezone.utc).isoformat()
            if self.finished_at
            else None,
            "summary": self.summary(),
            "findings": [f.to_dict() for f in self.findings],
            "dependency_findings": [d.to_dict() for d in self.dependency_findings],
            "errors": [asdict(e) for e in self.errors],
            "partial": self.partial,
        }

    @classmethod
    def from_dict(cls, d: dict) -> ScanResult:
        return cls(
            target=d["target"],
            started_at=datetime.fromisoformat(d["started_at"]),
            finished_at=datetime.fromisoformat(d["finished_at"]) if d["finished_at"] else None,
            findings=[Finding.from_dict(x) for x in d["findings"]],
            dependency_findings=[DependencyFinding.from_dict(x) for x in d["dependency_findings"]],
            files_scanned=d["summary"]["files_scanned"],
            dependencies_scanned=d["summary"]["dependencies_scanned"],
            errors=[ScanError(**e) for e in d["errors"]],
            partial=d["partial"],
            tool_version=d.get("tool_version", TOOL_VERSION),
        )
